server:
  port: 2020

#config:
#  rest:
#    service:
#      studenturl: http://localhost:8099/test/v1/employee


config:
  rest:
    service:
      addStudentUrl: http://localhost:8099/test/v1/employee
spring:
  mvc:
    path match:
      matching-strategy: ant-path-matcher

app:
  name: spring boot application
  api:
    title: Spring Boot APIs
    version: 3.0.0
    description: Spring Boot APIs description
    base-package: training.acabes.mock
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: false