server:
  port: 8099
  servlet:
    context-path: /test/v1

spring:
  data:
    mongodb:
      user: admin
      password: admin
      database: study
      uri: mongodb://localhost:27017


  mvc:
    path match:
      matching-strategy: ant-path-matcher

app:
  name: spring boot application
  api:
    title: Spring Boot APIs
    version: 3.0.0
    description: Spring Boot APIs description
    base-package: training.acabes.mock
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: false