

config:
  rest:
    service:
      getLoanUrl: http://localhost:1414/management/v1/loan-request
spring:
  mvc:
    path match:
      matching-strategy: ant-path-matcher

app:
  name: spring boot application
  api:
    title: Spring Boot APIs
    version: 3.0.0
    description: Spring Boot APIs description
    base-package: training.acabes.mock
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: false